apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-brannslukning
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  leaderElection: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: '77cce29b-3cb8-45f7-8014-a551fb93f8a6'
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: tms-brannslukning
        type: POSTGRES_15
        tier: db-f1-micro
        diskType: SSD
        diskSize: 10
        diskAutoresize: false
        autoBackupTime: "03:00"
        databases:
          - name: brannslukning
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 512Mi
